### ISSUE TITLE
Error in tests (Dropdown)

### ISSUE THREAD

**Issue by aaronmaturen** [cengage/react-magma#111]
PASS react-magma-dom packages/react-magma-dom/src/components/Dropdown/Dropdown.test.js
  ● Console

    console.error
      Warning: An update to ForwardRef inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in ForwardRef

      225 | 
      226 |         if (!isInMenu && isOpen) {
    > 227 |           setIsOpen(false);
          |           ^
      228 |         }
      229 |       }, 0);
      230 |     }

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:23284:7)
      at setIsOpen (node_modules/react-dom/cjs/react-dom.development.js:15656:9)
      at packages/react-magma-dom/src/components/Dropdown/index.tsx:227:11
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:391:19)

    console.error
      Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
          in ForwardRef

      225 | 
      226 |         if (!isInMenu && isOpen) {
    > 227 |           setIsOpen(false);
          |           ^
      228 |         }
      229 |       }, 0);
      230 |     }

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnAboutUpdateOnUnmountedFiberInDEV (node_modules/react-dom/cjs/react-dom.development.js:23161:5)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21169:5)
      at setIsOpen (node_modules/react-dom/cjs/react-dom.development.js:15660:5)
      at packages/react-magma-dom/src/components/Dropdown/index.tsx:227:11
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:391:19)

**Comment by silvalaura** [comment]
Closing in favor of https://github.com/cengage/react-magma/issues/1018
