### ISSUE TITLE
Investigate warning: `@import` rules can't be after other rules.

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#1604]
Multiple adopter apps (authoring-ui, mts-caldera, mts-ui, etc.) are seeing the following warning in their consoles:
```
`@import` rules can't be after other rules. Please put your `@import` rules before your other rules. Error Component Stack
    at emotion-element-489459f2.browser.development.esm.js:33:27
    at GlobalStyles (index.js:24740:1)
    at option-sets.provider.tsx:9:13
    at DefaultErrorBoundary (eval at ES6ProxyComponentFactory (react-hot-loader.development.js:335:10), DefaultErrorBoundary:14:7)
    at App (App.tsx:60:9)
    at AppContainer (eval at ES6ProxyComponentFactory (react-hot-loader.development.js:335:10), AppContainer:14:7)
    at HotExportedApp (eval at ES6ProxyComponentFactory (react-hot-loader.development.js:335:10), HotExportedApp:14:7)
    at Provider (Provider.js:7:1)
    at Index (<anonymous>)
    at Suspense (<anonymous>)
    at EditActivityLauncher (EditActivityLauncher.tsx:43:5)
    at div (<anonymous>)
    at EditActivityWrapper (EditActivityWrapper.tsx:13:13)
    at div (<anonymous>)
    at emotion-element-489459f2.browser.development.esm.js:33:27
    at TabPanel.tsx:36:13
    at div (<anonymous>)
    at emotion-element-489459f2.browser.development.esm.js:33:27
    at TabPanelsContainer.tsx:21:11
    at div (<anonymous>)
    at emotion-element-489459f2.browser.development.esm.js:33:27
    at TabsContainer.tsx:50:11
    at AuthoringLauncher (AuthoringLauncher.tsx:65:53)
    at div (<anonymous>)
    at emotion-element-489459f2.browser.development.esm.js:33:27
    at TabPanel.tsx:36:13
    at div (<anonymous>)
    at emotion-element-489459f2.browser.development.esm.js:33:27
    at TabPanelsContainer.tsx:21:11
    at div (<anonymous>)
    at emotion-element-489459f2.browser.development.esm.js:33:27
    at TabsContainer.tsx:50:11
    at SplitTreatments (eval at ES6ProxyComponentFactory (react-hot-loader.development.js:335:10), SplitTreatments:14:7)
    at StarshipBridge (<anonymous>)
    at main (<anonymous>)
    at SplitComponent (eval at ES6ProxyComponentFactory (react-hot-loader.development.js:335:10), SplitComponent:14:7)
    at SplitFactoryProvider (SplitFactoryProvider.js:23:14)
    at DefaultErrorBoundary (eval at ES6ProxyComponentFactory (react-hot-loader.development.js:335:10), DefaultErrorBoundary:14:7)
    at Starship (Starship.tsx:18:65)
    at AppContainer (eval at ES6ProxyComponentFactory (react-hot-loader.development.js:335:10), AppContainer:14:7)
    at HotExportedStarship (eval at ES6ProxyComponentFactory (react-hot-loader.development.js:335:10), HotExportedStarship:14:7)
```

I believe this could be related to our upgrade to emotion 11. We need to investigate this and figure out how to remove this from our adopters' console.

**Comment by silvalaura** [comment]
Confirmed that I no longer see the `@import` rules can't be after other rules.` error when pulling react-magma-dom `4.8.0-next.4` on caldera-ui.
